name: dockerbuild

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          project_id: mythical-games
      - name: GCloud Init
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev
      - name: Build and push docker image
        run: |
            docker build -t us-docker.pkg.dev/mythical-games/saga/smtp-blackhole:latest .
            docker push us-docker.pkg.dev/mythical-games/saga/smtp-blackhole:latest